### ISSUE TITLE
Pay our bills

### ISSUE THREAD

**Issue by bjacobel** [BowdoinOrient/bongo#27]
Develop a plan for paying for our tech stack in perpetuity. That stack is:
- [ ] Domain registrar (currently Hover, see #21)
- [ ] DNS provider (currently AWS Route 53, also see #21)
- [ ] Hosting provider (currently Digital Ocean, see #26)
- [ ] Static files host (currently AWS S3)
- [ ] CDN provider (see #22)
- [ ] Typekit (see #42)

If the plan is "Brian pays for it" that's what it is, but Orient leadership should be aware of the costs & who to contact about it.

Free stuff we're currently using I hope we won't need to upgrade to paid plans on:
- Travis CI
- Github
- Sentry
- Logentries
- New Relic
